# French Creek Pollution Control Centre

In [1]:
import datetime as dt
import gsw
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.io as sio
import xarray as xr
import PyCO2SYS as pyco2

In [5]:
j=551	
i=171

## Temperature (deg C)

In [2]:
temp_2023 = np.array([13.8, 13.4, 13.4, 14.3, 17.6, 19.3, 21.0, 21.1, 19.9, 18.1, 16.0, 15.1])
temp_2024 = np.array([13.8, 13.4, 13.4, 14.3, 17.6, 19.3, 21.0, 21.1, 19.9, 18.1, 16.0, 15.1])
temp_2025 = np.array([13.7, 13.0, 14.1, 15.6, 17.4, 19.1, 20.8, 21.1, 20.5, 17.8, 16.4, 15.2])
temp = (temp_2023+temp_2024+temp_2025)/3
temp

array([13.76666667, 13.26666667, 13.63333333, 14.73333333, 17.53333333,
       19.23333333, 20.93333333, 21.1       , 20.1       , 18.        ,
       16.13333333, 15.13333333])

In [3]:
# Conservative temperature 
temp_conservative = gsw.CT_from_pt(0, temp)
print(temp_conservative)

[14.50703609 13.98219844 14.36708686 15.52151188 18.45860186 20.24097139
 22.02279929 22.19746224 21.14941667 18.94793865 16.99029848 15.94121794]


## Flux (m^3/day)

In [4]:
flux_m3d_2023 = np.array([10843.8, 9949.7, 10455.9, 10093.4, 10171.7, 10252.8, 10315.7, 10315.7, 9757.7, 10449.7, 10565.8, 11758.5])
flux_m3d_2024 = np.array([12043.8, 11083.4, 11193.8, 10365.3, 10250.7, 10108.7, 10595.1, 10750.4, 9896.8, 10143.0, 11776.7, 11896.0])
flux_m3d_2025 = np.array([10583.6, 10670.5, 11641.1, 10480.9, 10238.1, 10438.4, 10902.0, 10979.8, 10216.6, 10006.6, 10430.5, 11560.1])
flux_m3d = (flux_m3d_2023+flux_m3d_2024+flux_m3d_2025)/3
flux_m3d

array([11157.06666667, 10567.86666667, 11096.93333333, 10313.2       ,
       10220.16666667, 10266.63333333, 10604.26666667, 10681.96666667,
        9957.03333333, 10199.76666667, 10924.33333333, 11738.2       ])

In [6]:
mesh_mask_nc = "/ocean/atall/MOAD/grid/mesh_mask_202310b.nc"
ds_mask = xr.open_dataset(mesh_mask_nc)
rho = 1000
seconds_per_day = 86400
cell_area = (ds_mask["e1t"].isel(t=0).values[j, i]* ds_mask["e2t"].isel(t=0).values[j, i])
new_flux = (flux_m3d * rho/ (cell_area * seconds_per_day))
print("New flux:", new_flux)
print("New flux is in kg/m2/S")

New flux: [0.00060258 0.00057076 0.00059933 0.000557   0.00055198 0.00055449
 0.00057272 0.00057692 0.00053777 0.00055088 0.00059001 0.00063396]
New flux is in kg/m2/S


## Ammonia (mg/L)

In [7]:
ammonia_2023 = np.array([29.3, 29.5, 31.2, 26.7, 29.1, 33.7, 36.2, 38.2, 34.3, 28.5, 25.5, 24.1])
ammonia_2024 = np.array([23.5, 24.1, 29.1, 28.7, 33.3, 31.3, 35.8, 37.5, 32.9, 31.6, 27.4, 27.8])
ammonia_2025 = np.array([29.5, 34.6, 30.7, 37.0, 35.1, 38.2, 41.1, 47.4, 45.1, 38.6, 36.0, 32.4])
ammonia = (ammonia_2023 + ammonia_2024+ammonia_2025)/3
ammonia

array([27.43333333, 29.4       , 30.33333333, 30.8       , 32.5       ,
       34.4       , 37.7       , 41.03333333, 37.43333333, 32.9       ,
       29.63333333, 28.1       ])

In [8]:
# Convert mg/L NH3 to mmol/m³
molar_mass_NH3 = 17.031  # g/mol
ammonia_mmol_m3 = ammonia * 1000 / molar_mass_NH3
print(ammonia_mmol_m3)

[1610.78817059 1726.26387176 1781.06589944 1808.46691328 1908.28489226
 2019.84616288 2213.61047502 2409.33200243 2197.95275282 1931.77147554
 1739.96437868 1649.93247607]


## Alkalinity (mg/L)

In [9]:
alkalinity_2023 = np.array([223, 214, 231, 205, 236, 202, 243, 256, 259, 205, 231, 186])
alkalinity_2024 = np.array([190, 196, 192, 224, 238, 204, 171, 162, 181, 203, 164, 170])
alkalinity_2025 = np.array([176, 206, 219, 239, 233, 232, 244, 253, 229, 236, 188, 205])
alkalinity = (alkalinity_2023 + alkalinity_2024 + alkalinity_2025) / 3
alkalinity

array([196.33333333, 205.33333333, 214.        , 222.66666667,
       235.66666667, 212.66666667, 219.33333333, 223.66666667,
       223.        , 214.66666667, 194.33333333, 187.        ])

In [10]:
# mg/L as CaCO3 to mmol/m³ of alkalinity
alkalinity_mmol_m3 = alkalinity * 1000 / 100.0869 * 2
print(alkalinity_mmol_m3)

[3923.25735602 4103.10107184 4276.28390928 4449.46674673 4709.2410029
 4249.64039583 4382.8579631  4469.44938182 4456.12762509 4289.60566601
 3883.29208584 3736.75276185]


## BOD (mg/L)

In [12]:
bod_2023 = np.array([15.6, 14.4, 14.4, 15.8, 13.1, 11.7, 10.4, 11.6, 9.6, 9.4, 8.3,10.6])
bod_2024 = np.array([14.9, 16.0, 17.0, 20.6, 16.7, 10.3, 12.7, 12.7, 9.5, 11.6, 11.4, 12.1])
bod_2025 = np.array([17.4, 22.2, 19.5, 13.7, 12.9, 15.0, 12.7, 14.1, 13.2, 12.1, 11.3, 13.6])
bod = (bod_2023 + bod_2024 + bod_2025) / 3
bod

array([15.96666667, 17.53333333, 16.96666667, 16.7       , 14.23333333,
       12.33333333, 11.93333333, 12.8       , 10.76666667, 11.03333333,
       10.33333333, 12.1       ])

## PON and DON

In [13]:
# Convert BOD from mg O2/L to mmol O2/m3,then estimate biodegradable organic carbon in mmol C/m3
boc_mmol_m3 = bod * 1000 / 32 * 106 / 138
# Assumed molar carbon-to-nitrogen ratio
carbon_to_nitrogen_ratio = 34
# Assumption: DOC = 0.8 * POC
doc_to_poc_ratio = 0.8
# Split biodegradable organic carbon into particulate and dissolved carbon
poc_mmol_m3 = boc_mmol_m3 / (1 + doc_to_poc_ratio)
doc_mmol_m3 = poc_mmol_m3 * doc_to_poc_ratio
# Convert particulate and dissolved carbon to organic nitrogen
PON = poc_mmol_m3 / carbon_to_nitrogen_ratio
DON = doc_mmol_m3 / carbon_to_nitrogen_ratio

print("Estimated PON in mmol N/m3:")
print(PON)

print("\nEstimated DON in mmol N/m3:")
print(DON)

Estimated PON in mmol N/m3:
[6.26238317 6.87685501 6.65459924 6.55000829 5.58254199 4.83733147
 4.68044504 5.02036563 4.22285963 4.32745059 4.05289934 4.74581439]

Estimated DON in mmol N/m3:
[5.00990654 5.50148401 5.32367939 5.24000663 4.4660336  3.86986518
 3.74435604 4.01629251 3.37828771 3.46196047 3.24231947 3.79665151]


## pH

In [14]:
ph_2023 = np.array([7.08, 7.30, 7.33, 7.30, 7.25, 7.26, 7.26, 7.31, 7.28, 7.17, 7.15, 7.20])
ph_2024 = np.array([7.30, 7.27, 7.28, 7.24, 7.23, 7.28, 7.29, 7.29, 7.31, 7.26, 7.29, 7.31])
ph_2025 = np.array([7.34, 7.36, 7.39, 7.45, 7.47, 7.46, 7.45, 7.42, 7.42, 7.31, 7.33, 7.31])
ph = (ph_2023 + ph_2024 + ph_2025) / 3
ph

array([7.24      , 7.31      , 7.33333333, 7.33      , 7.31666667,
       7.33333333, 7.33333333, 7.34      , 7.33666667, 7.24666667,
       7.25666667, 7.27333333])

## DIC

In [15]:
# At density = 1000 kg/m3: mmol/m3 is numerically approximately equal to µmol/kg
alkalinity_umol_kg = alkalinity_mmol_m3

kwargs = dict(par1_type=1, par1=alkalinity_umol_kg,    # Total alkalinity
    par2_type=3,par2=ph,                               # pH
    salinity=0.4,
    temperature=temp,
    pressure=0,
    total_silicate=137,       
    total_phosphate=0,           
    opt_pH_scale=4,            
    opt_k_carbonic=8,
    opt_k_bisulfate=1,
    opt_total_borate=1,
)

results = pyco2.sys(**kwargs)
dic_umol_kg = results["dic"]
rho = 1000.0  # kg/m3
dic_mmol_m3 = dic_umol_kg * rho / 1000
print("Monthly DIC in mmol/m3:")
print(dic_mmol_m3)

Monthly DIC in mmol/m3:
[4527.65856976 4645.60272712 4807.74948485 4994.76082588 5274.57199585
 4726.2420922  4861.21811821 4948.45338181 4945.06230133 4891.05649494
 4433.21101925 4255.40985666]


## TSS (mg/L)

In [16]:
tss_2023 = np.array([18.7, 14.2, 15.5, 15.5, 16.3, 13.9, 12.7, 13.1, 15.4, 16.4, 19.3, 18.4])
tss_2024 = np.array([20.6, 22.1, 20.0, 20.9, 18.6, 13.8, 15.5, 14.5, 12.2, 19.5, 17.6, 24.0])
tss_2025 = np.array([22.5, 26.0, 20.1, 12.9, 10.9, 16.0, 17.1, 14.0, 13.9, 16.3, 15.2, 19.5])
tss = (tss_2023 + tss_2024 + tss_2025) / 3
tss

array([20.6       , 20.76666667, 18.53333333, 16.43333333, 15.26666667,
       14.56666667, 15.1       , 13.86666667, 13.83333333, 17.4       ,
       17.36666667, 20.63333333])

## Turbidity

In [17]:
turbidity_fau = (tss - 7) / 0.89
print("Turbidity in FAU:")
print(turbidity_fau)

Turbidity in FAU:
[15.28089888 15.46816479 12.9588015  10.59925094  9.28838951  8.50187266
  9.1011236   7.71535581  7.67790262 11.68539326 11.64794007 15.31835206]


## Nitrate (mg/L)

In [18]:
nitrate_2023 = np.array([1.65, 1.980, 2.238, 2.39, 2.38, 2.51, 1.86, 0.93, 1.39, 2.02, 2.76, 2.66])
nitrate_2024 = np.array([3.00, 3.23, 1.64, 1.56, 1.25, 3.39, 1.88, 1.57, 4.05, 2.61, 2.78, 1.92])
nitrate_2025 = np.array([1.90, 1.08, 0.914, 1.33, 1.09, 1.01, 0.93, 0.894, 1.05, 1.90, 1.72, 2.27])
nitrate = (nitrate_2023 + nitrate_2024 + nitrate_2025) / 3
nitrate

array([2.18333333, 2.09666667, 1.59733333, 1.76      , 1.57333333,
       2.30333333, 1.55666667, 1.13133333, 2.16333333, 2.17666667,
       2.42      , 2.28333333])

In [19]:
nitrate_mmol_m3 = nitrate * 1000 / 62.0
nitrate_mmol_m3

array([35.21505376, 33.8172043 , 25.76344086, 28.38709677, 25.37634409,
       37.15053763, 25.10752688, 18.24731183, 34.89247312, 35.10752688,
       39.03225806, 36.82795699])

## Oxygen (mg/L)

In [20]:
oxygen_2023 = np.array([5.41, 5.51, 5.50, 5.28, 5.31, 5.49, 5.49, 5.04, 5.12, 5.36, 5.55, 5.61])
oxygen_2024 = np.array([5.54, 5.45, 5.64, 5.37, 5.29, 5.43, 5.53, 5.55, 5.88, 5.75, 5.79, 5.70])
oxygen_2025 = np.array([5.58, 5.46, 5.50, 3.37, 2.88, 3.40, 2.93, 3.11, 3.20, 3.34, 3.31, 3.54])
oxygen = (oxygen_2023 + oxygen_2024 + oxygen_2025) / 3
oxygen

array([5.51      , 5.47333333, 5.54666667, 4.67333333, 4.49333333,
       4.77333333, 4.65      , 4.56666667, 4.73333333, 4.81666667,
       4.88333333, 4.95      ])

In [21]:
oxygen_mmol_m3 = oxygen * 1000 / 32.0
oxygen_mmol_m3

array([172.1875    , 171.04166667, 173.33333333, 146.04166667,
       140.41666667, 149.16666667, 145.3125    , 142.70833333,
       147.91666667, 150.52083333, 152.60416667, 154.6875    ])

In [22]:
dSi = np.zeros(12)
diatoms = np.zeros(12)
nanoflagellates = np.zeros(12)
z1 = np.zeros(12)
bSi = np.zeros(12)